[package]
name = "seamless"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.11.2"
bevy_flycam = { path = "../../lib/bevy_flycam" }
bevy_egui = { version = "0.21.0" }
bevy_voxel = { path = "../../lib/bevy_voxel" }
voxels = { path = "../../lib/voxels" }


